# TODO: Add license info

[package]
name = "icu4x-js-regexp"
version = "0.1.0"
authors = ["Iain Ireland <iireland@mozilla.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
path = "src/lib.rs"

[dependencies]
icu_provider = { git = "https://github.com/iainireland/icu4x.git", rev = "66910f11e7a6047f7ea78b5c5596d5f9c55a29fc" }
icu_provider_blob = { git = "https://github.com/iainireland/icu4x.git", rev = "66910f11e7a6047f7ea78b5c5596d5f9c55a29fc", features = ["export"] }
icu_provider_uprops = { git = "https://github.com/iainireland/icu4x.git", rev = "66910f11e7a6047f7ea78b5c5596d5f9c55a29fc" }
icu_uniset = { git = "https://github.com/iainireland/icu4x.git", rev = "66910f11e7a6047f7ea78b5c5596d5f9c55a29fc" }
